static char *win7_sp1_x64_wship6_guid[2] = {
	"4a5be0b107000",
	"be71ccca26764d10836e941b34dec9d22"
	};
static struct symbol win7_sp1_x64_wship6[] = {
	{.name = "TcpMappingTriples", .rva = 0x3580},
	{.name = "__security_cookie_complement", .rva = 0x3000},
	{.name = "__imp_RtlInitUnicodeString", .rva = 0x2058},
	{.name = "TcpipProviderGuid", .rva = 0x3ee0},
	{.name = "_string_", .rva = 0x2318},
	{.name = "WSHOpenSocket", .rva = 0x1850},
	{.name = "WSHIoctl", .rva = 0x1c98},
	{.name = "__imp_LdrDisableThreadCalloutsForDll", .rva = 0x2068},
	{.name = "__imp_RtlAppendUnicodeStringToString", .rva = 0x2010},
	{.name = "RawMappingTriples", .rva = 0x3700},
	{.name = "WSHAddressToString", .rva = 0x1010},
	{.name = "__security_init_cookie_ex", .rva = 0x14b0},
	{.name = "_string__2", .rva = 0x2278},
	{.name = "RtlUnhandledExceptionFilter", .rva = 0x1dac},
	{.name = "RtlCaptureContext", .rva = 0x1dd0},
	{.name = "memmove", .rva = 0x1d94},
	{.name = "__GSHandlerCheckCommon", .rva = 0x1ddc},
	{.name = "WSHOpenSocket2", .rva = 0x11f0},
	{.name = "__imp_RtlAllocateHeap", .rva = 0x2018},
	{.name = "__imp_RtlIpv6AddressToStringExW", .rva = 0x2000},
	{.name = "__imp_RtlIpv4AddressToStringExW", .rva = 0x2008},
	{.name = "__imp_NtTerminateProcess", .rva = 0x2030},
	{.name = "WSHGetProviderGuid", .rva = 0x1c4c},
	{.name = "__imp__wcsicmp", .rva = 0x2070},
	{.name = "__imp_RtlCaptureContext", .rva = 0x2050},
	{.name = "WSHGetWinsockMapping", .rva = 0x17e0},
	{.name = "__imp_ntohs", .rva = 0x2080},
	{.name = "__GSHandlerCheck", .rva = 0x1e48},
	{.name = "g_TdiModeDgram", .rva = 0x35d8},
	{.name = "Winsock2Protocols", .rva = 0x3780},
	{.name = "_string__3", .rva = 0x2298},
	{.name = "UdpMappingTriples", .rva = 0x35b0},
	{.name = "WSHGetWildcardSockaddr", .rva = 0x13d8},
	{.name = "$$VProc_ImageExportDirectory", .rva = 0x20a0},
	{.name = "__imp_setsockopt", .rva = 0x2088},
	{.name = "_DllMainCRTStartupForGS", .rva = 0x142c},
	{.name = "__imp_RtlIntegerToUnicodeString", .rva = 0x2028},
	{.name = "RtlLookupFunctionEntry", .rva = 0x1dc4},
	{.name = "NtTerminateProcess", .rva = 0x1da0},
	{.name = "WSHGetSocketInformation", .rva = 0x11a0},
	{.name = "g_TdiModeRaw", .rva = 0x3ef0},
	{.name = "WSHEnumProtocols", .rva = 0x18d8},
	{.name = "_string__4", .rva = 0x22c8},
	{.name = "__security_check_cookie", .rva = 0x1580},
	{.name = "WSHJoinLeaf", .rva = 0x1ac8},
	{.name = "__imp_WSAGetLastError", .rva = 0x2090},
	{.name = "WSHNotify", .rva = 0x1890},
	{.name = "__imp_RtlLookupFunctionEntry", .rva = 0x2048},
	{.name = "WSHGetSockaddrType", .rva = 0x1138},
	{.name = "__imp_RtlIpv6StringToAddressExW", .rva = 0x2020},
	{.name = "_string__5", .rva = 0x22e8},
	{.name = "__imp_RtlVirtualUnwind", .rva = 0x2040},
	{.name = "WSHSetSocketInformation", .rva = 0x1560},
	{.name = "HotPatchBuffer", .rva = 0x35f0},
	{.name = "__imp_RtlUnhandledExceptionFilter", .rva = 0x2038},
	{.name = "WSHStringToAddress", .rva = 0x10a0},
	{.name = "__security_cookie", .rva = 0x35e0},
	{.name = "__security_init_cookie", .rva = 0x1460},
	{.name = "__imp_memmove", .rva = 0x2060},
	{.name = "RtlVirtualUnwind", .rva = 0x1db8},
	{.name = "__report_gsfailure", .rva = 0x1ca4},
	{.name = "_string__6", .rva = 0x2300},
	{.name = "WSHGetWSAProtocolInfo", .rva = 0x1be8},
	{.name = "g_TdiModeStream", .rva = 0x35a8},

};
static uint64_t win7_sp1_x64_wship6_count = 64;
